version: '3.7'
services:
  # postgres:
  #   image: postgres:9.6
  #   container_name: postgres
  #   environment:
  #     - POSTGRES_USER=airflow
  #     - POSTGRES_PASSWORD=airflow
  #     - POSTGRES_DB=airflow
  # airflow:
  #   build: './airflow_docker'
  #   container_name: airflow
  #   restart: always
  #   depends_on:
  #     - postgres
  #   environment:
  #     - LOAD_EX=n
  #     - EXECUTOR=Local
  #   volumes:
  #     - ./dags:/usr/local/airflow/dags
  #   ports:
  #     - "8080:8080"
  #   command: webserver
  #   healthcheck:
  #     test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
  ubuntu:
    build: './ubuntu_docker'
    container_name: ubuntu
    ports:
      - '5000:22'
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    
